String codeToNameFunction(String code) {
  if (code == "ab") return "Abkhaz";
  if (code == "aa") return "Afar";
  if (code == "af") return "Afrikaans";
  if (code == "ak") return "Akan";
  if (code == "sq") return "Albanian";
  if (code == "am") return "Amharic";
  if (code == "ar") return "Arabic";
  if (code == "an") return "Aragonese";
  if (code == "hy") return "Armenian";
  if (code == "as") return "Assamese";
  if (code == "av") return "Avaric";
  if (code == "ae") return "Avestan";
  if (code == "ay") return "Aymara";
  if (code == "az") return "Azerbaijani";
  if (code == "bm") return "Bambara";
  if (code == "ba") return "Bashkir";
  if (code == "eu") return "Basque";
  if (code == "be") return "Belarusian";
  if (code == "bn") return "Bengali";
  if (code == "bh") return "Bihari";
  if (code == "bi") return "Bislama";
  if (code == "bs") return "Bosnian";
  if (code == "br") return "Breton";
  if (code == "bg") return "Bulgarian";
  if (code == "my") return "Burmese";
  if (code == "ca") return "Catalan; Valencian";
  if (code == "ch") return "Chamorro";
  if (code == "ce") return "Chechen";
  if (code == "ny") return "Chichewa; Chewa; Nyanja";
  if (code == "zh") return "Chinese";
  if (code == "cv") return "Chuvash";
  if (code == "kw") return "Cornish";
  if (code == "co") return "Corsican";
  if (code == "cr") return "Cree";
  if (code == "hr") return "Croatian";
  if (code == "cs") return "Czech";
  if (code == "da") return "Danish";
  if (code == "dv") return "Divehi; Dhivehi; Maldivian;";
  if (code == "nl") return "Dutch";
  if (code == "en") return "English";
  if (code == "eo") return "Esperanto";
  if (code == "et") return "Estonian";
  if (code == "ee") return "Ewe";
  if (code == "fo") return "Faroese";
  if (code == "fj") return "Fijian";
  if (code == "fi") return "Finnish";
  if (code == "fr") return "French";
  if (code == "ff") return "Fula; Fulah; Pulaar; Pular";
  if (code == "gl") return "Galician";
  if (code == "ka") return "Georgian";
  if (code == "de") return "German";
  if (code == "el") return "Greek, Modern";
  if (code == "gn") return "Guaraní";
  if (code == "gu") return "Gujarati";
  if (code == "ht") return "Haitian; Haitian Creole";
  if (code == "ha") return "Hausa";
  if (code == "he") return "Hebrew (modern)";
  if (code == "hz") return "Herero";
  if (code == "hi") return "Hindi";
  if (code == "ho") return "Hiri Motu";
  if (code == "hu") return "Hungarian";
  if (code == "ia") return "Interlingua";
  if (code == "id") return "Indonesian";
  if (code == "ie") return "Interlingue";
  if (code == "ga") return "Irish";
  if (code == "ig") return "Igbo";
  if (code == "ik") return "Inupiaq";
  if (code == "io") return "Ido";
  if (code == "is") return "Icelandic";
  if (code == "it") return "Italian";
  if (code == "iu") return "Inuktitut";
  if (code == "ja") return "Japanese";
  if (code == "jv") return "Javanese";
  if (code == "kl") return "Kalaallisut, Greenlandic";
  if (code == "kn") return "Kannada";
  if (code == "kr") return "Kanuri";
  if (code == "ks") return "Kashmiri";
  if (code == "kk") return "Kazakh";
  if (code == "km") return "Khmer";
  if (code == "ki") return "Kikuyu, Gikuyu";
  if (code == "rw") return "Kinyarwanda";
  if (code == "ky") return "Kirghiz, Kyrgyz";
  if (code == "kv") return "Komi";
  if (code == "kg") return "Kongo";
  if (code == "ko") return "Korean";
  if (code == "ku") return "Kurdish";
  if (code == "kj") return "Kwanyama, Kuanyama";
  if (code == "la") return "Latin";
  if (code == "lb") return "Luxembourgish, Letzeburgesch";
  if (code == "lg") return "Luganda";
  if (code == "li") return "Limburgish, Limburgan, Limburger";
  if (code == "ln") return "Lingala";
  if (code == "lo") return "Lao";
  if (code == "lt") return "Lithuanian";
  if (code == "lu") return "Luba-Katanga";
  if (code == "lv") return "Latvian";
  if (code == "gv") return "Manx";
  if (code == "mk") return "Macedonian";
  if (code == "mg") return "Malagasy";
  if (code == "ms") return "Malay";
  if (code == "ml") return "Malayalam";
  if (code == "mt") return "Maltese";
  if (code == "mi") return "Māori";
  if (code == "mr") return "Marathi (Marāṭhī)";
  if (code == "mh") return "Marshallese";
  if (code == "mn") return "Mongolian";
  if (code == "na") return "Nauru";
  if (code == "nv") return "Navajo, Navaho";
  if (code == "nb") return "Norwegian Bokmål";
  if (code == "nd") return "North Ndebele";
  if (code == "ne") return "Nepali";
  if (code == "ng") return "Ndonga";
  if (code == "nn") return "Norwegian Nynorsk";
  if (code == "no") return "Norwegian";
  if (code == "ii") return "Nuosu";
  if (code == "nr") return "South Ndebele";
  if (code == "oc") return "Occitan";
  if (code == "oj") return "Ojibwe, Ojibwa";
  if (code == "om") return "Oromo";
  if (code == "or") return "Oriya";
  if (code == "os") return "Ossetian, Ossetic";
  if (code == "pa") return "Panjabi, Punjabi";
  if (code == "pi") return "Pāli";
  if (code == "fa") return "Persian";
  if (code == "pl") return "Polish";
  if (code == "ps") return "Pashto, Pushto";
  if (code == "pt") return "Portuguese";
  if (code == "qu") return "Quechua";
  if (code == "rm") return "Romansh";
  if (code == "rn") return "Kirundi";
  if (code == "ro") return "Romanian, Moldavian, Moldovan";
  if (code == "ru") return "Russian";
  if (code == "sa") return "Sanskrit (Saṁskṛta)";
  if (code == "sc") return "Sardinian";
  if (code == "sd") return "Sindhi";
  if (code == "se") return "Northern Sami";
  if (code == "sm") return "Samoan";
  if (code == "sg") return "Sango";
  if (code == "sr") return "Serbian";
  if (code == "gd") return "Scottish Gaelic; Gaelic";
  if (code == "sn") return "Shona";
  if (code == "si") return "Sinhala, Sinhalese";
  if (code == "sk") return "Slovak";
  if (code == "sl") return "Slovene";
  if (code == "so") return "Somali";
  if (code == "st") return "Southern Sotho";
  if (code == "es") return "Spanish; Castilian";
  if (code == "su") return "Sundanese";
  if (code == "sw") return "Swahili";
  if (code == "ss") return "Swati";
  if (code == "sv") return "Swedish";
  if (code == "ta") return "Tamil";
  if (code == "te") return "Telugu";
  if (code == "tg") return "Tajik";
  if (code == "th") return "Thai";
  if (code == "ti") return "Tigrinya";
  if (code == "bo") return "Tibetan Standard, Tibetan, Central";
  if (code == "tk") return "Turkmen";
  if (code == "tl") return "Tagalog";
  if (code == "tn") return "Tswana";
  if (code == "to") return "Tonga (Tonga Islands)";
  if (code == "tr") return "Turkish";
  if (code == "ts") return "Tsonga";
  if (code == "tt") return "Tatar";
  if (code == "tw") return "Twi";
  if (code == "ty") return "Tahitian";
  if (code == "ug") return "Uighur, Uyghur";
  if (code == "uk") return "Ukrainian";
  if (code == "ur") return "Urdu";
  if (code == "uz") return "Uzbek";
  if (code == "ve") return "Venda";
  if (code == "vi") return "Vietnamese";
  if (code == "vo") return "Volapük";
  if (code == "wa") return "Walloon";
  if (code == "cy") return "Welsh";
  if (code == "wo") return "Wolof";
  if (code == "fy") return "Western Frisian";
  if (code == "xh") return "Xhosa";
  if (code == "yi") return "Yiddish";
  if (code == "yo") return "Yoruba";
  if (code == "za") return "Zhuang, Chuang";
  return code;
}
