name: tgh_task
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  debounce_throttle: ^2.0.0
  dio: ^5.3.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
